### ISSUE TITLE
greater-than sign in parametrized values (to check function return values)

### ISSUE THREAD

**Issue by jakkdl** [typeddjango/pytest-mypy-plugins#110]
```yaml
- case: foo
  parametrized:
    - val: bool
      rt: 'def (builtins.object =) -> builtins.bool'
  main: |
    reveal_type({{ val }})  # N: Revealed type is "{{ rt }}"
```

```
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Invalid output: 
E   Actual:
E     main:1: note: Revealed type is "def (builtins.object =) -> builtins.bool" (diff)
E   Expected:
E     main:1: note: Revealed type is "def (builtins.object =) -&gt; bool" (diff)
E   Alignment of first line difference:
E     E: ... "def (builtins.object =) -&gt; bool"
E     A: ... "def (builtins.object =) -> builtins.bool"
E                                      ^
```

This is not due to yaml, but due to chevron escaping html characters. Only way to get around it is to not use parametrized, which makes for a lot more repeated code
