### ISSUE TITLE
[tool.mypy.overrides] sections are dropped from config

### ISSUE THREAD

**Issue by ap--** [typeddjango/pytest-mypy-plugins#145]
Hello everyone,

I noticed that when using `pyproject.toml` to configure mypy, the pytest-mypy-plugins plugin silently drops overrides sections:

```toml
[[tool.mypy.overrides]]
module = "mymodule"
ignore_missing_imports = true
```

I have a PR ready to fix this, and will push it right away.

Cheers,
Andreas 😃
