### ISSUE TITLE
Add `mark` support

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/pytest-mypy-plugins#32]
Sometimes I want to run all `FutureResult` (or tests for any other type) related tests from `returns`.
It is a very complex task right now.

I need to:
1. manually find all `FutureResult` inside tests
2. manually copy all the paths from the query
3. provide long list of arguments to `pytest`

All I want instead is:

```yml
- case: test_future_result
   marks:
     - future_result
  main: ...
```

And then `pytest -m future_result` to run this (and all other similarly marked tests).

**Comment by kornicameister** [comment]
Can be done, but marks on its own can have parameters `i.e. mode(mode_name)` where `mode_name` is a placeholder.
Any idea for possible syntax to support that? 

Also...`pytest` warns if you use undefined mark; but I guess that has to stay. You define a mark and later on can use the mark either in `yml` or `py` test file, right?

**Comment by sobolevn** [comment]
> Any idea for possible syntax to support that?

No ideas! Do you have any?

**Comment by kornicameister** [comment]
Dunno :P
I guess something to resemble normal pytest should be most efficient:

```yml
- case: lol
  mark:
    - blockchain
    - module(api)
```

pytest:ini
```ini
[pytest]
marks = 
   blockchain: ...
   module(m): ...
```

?
