### ISSUE TITLE
PYTHONPATH and MYPYPATH cannot be specified in `env:` directive

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/pytest-mypy-plugins#43]
Currently this code does not work:

```yml
-   case: mypy_path_from_env
    main: |
        from pair import Pair

        a: Pair
        reveal_type(a)  # N: Revealed type is 'pair.Pair'
    env:
        - MYPYPATH=./pytest_mypy_plugins/tests/fixtures
```

Because currently `pytest-mypy-plugins` does not respect this way of defining variables.
