### ISSUE TITLE
Skipping tests conditionally

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/pytest-mypy-plugins#9]
Let's think about how a test can be skipped. I suggest the following api:

```yaml
- case: test_with_skip
   skip: python_value_or_expression_to_eval
   main: reveal_type('')  # N: builtins.str
```

This way we can skip some tests on different python versions or missing dependencies.

## Eval context

The tricky part here is the eval context. What should be there? 

## Related

- http://doc.pytest.org/en/latest/skipping.html
