### ISSUE TITLE
mypy_config documentation is confusing

### ISSUE THREAD

**Issue by whitphx** [typeddjango/pytest-mypy-plugins#94]
The `mypy_config` field accepts a string as below.
```yaml
- case: foo
  mypy_config:
    python_version = 3.8
```

So, if we want to provide multi fields, it would be like below, where the value of `mypy_config` in the YAML format is of type `str`.
```yaml
- case: foo
  mypy_config: |
    python_version = 3.8
    ignore_missing_imports = True
```

---

However, the document says its type is `Optional[Dict[str, Union[str, int, bool, float]]]={}` which I think means the following YAML format (dict syntax) is accepted.
```yaml
- case: foo
  mypy_config:
    python_version: 3.8
    ignore_missing_imports: true
```
but actually it is not.

---

My suggestion is either
* to change the documentation to say the type of `mypy_config` is `str`, or
* to change the implementation to accept the YAML dict.

because the `files` field, which is documented to accept `Optional[List[File]]=[]` type, can be specified with the YAML list syntax like
```yaml
    - path: myapp/__init__.py
```
, which is inconsistent and confusing.

---
The same problem is there on the `env` field.
Its type is documented as `Optional[Dict[str, str]]={}`, but the YAML syntax for the field is list as follows:
```yaml
  env:
    - MYPYPATH=./pytest_mypy_plugins/tests/fixtures
```
